title: Carsten Adams # your name (or website title) here
logo: "/images/Profile_Photo_cropped.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Data Scientist with 4+ years of experience in Data Analytics and Data Strategy in top tier firms. Former Assistant Manager at KPMG London, UK.
  <br><br>
  Data Scientist avec 4+ ans d’expérience dans l’analyse de données et la stratégie de données dans des entreprises de premier plan. Ancien Assistent Manager chez KPMG Londres.
  <br><br>
  Microsoft Certified:
  <br>
  <a href="https://www.credly.com/badges/9536831a-cbcc-4146-98f4-d3d7389e9c28/public_url">★★☆ Azure Data Scientist Associate</a><br>
  <a href="https://www.credly.com/badges/ea66ce52-c1d1-4c5f-9a50-5d7ac6b96f83/public_url">★☆☆ Azure AI Fundamentals</a><br>
  <a href="https://www.credly.com/badges/bc41ef06-5958-4e1b-b32f-afad9eed1f68/public_url">★☆☆ Azure Fundamentals</a><br><br>
  <a href="https://www.linkedin.com/in/carsten-adams-91307177/">View my LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'
